on: push

name: ci

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - run: |
        git clone -b windows_port --depth=1 https://github.com/jterry75/cri.git ~/go/src/github.com/containerd/containerd
        cd ~/go/src/github.com/containerd/containerd/cmd/containerd/
        go get
        go build -o ~/containerd.exe .
