on: push

name: containerd

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - run: |
        pwd 
        
        go env
        
        mkdir -Force $HOME/go/src/github.com/containerd
        mkdir -Force $HOME/containerd
        
        git clone -b windows_port --depth=1 https://github.com/jterry75/cri.git $HOME/go/src/github.com/containerd/cri
        cd $HOME/go/src/github.com/containerd/cri/cmd/containerd/
        
        go get
        
        ls $HOME/go/src
        
        go build -o $HOME/containerd/containerd.exe .
        ls $HOME
      name: Build  
#     - run: |
#         & "$HOME/containerd.exe"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: containerd
        path: "C:\\Users\\runneradmin\\containerd"
