on: push

name: ci

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - run: |
        pwd 
        go env
        mkdir -Force $HOME/go/src/github.com/containerd
        git clone -b windows_port --depth=1 https://github.com/jterry75/cri.git $HOME/go/src/github.com/containerd/containerd
        cd $HOME/go/src/github.com/containerd/containerd/cmd/containerd/
        go get -v
        ls
        go build -o $HOME/containerd.exe .
        ls $HOME
    - name: Upload artifacts (windows_amd64)
      uses: actions/upload-artifact@v1
      with:
        name: windows_amd64
        path: "C:\\Users\\runneradmin\\containerd.exe"
